jobs:
- template: azure-pipelines-uniz-windowx.yml
  parameters:
    jobName: macOS
    vmImage: macOS-10.13

- template: azure-pipelines-uniz-window.yml
  parameters:
    jobName: Linux
    vmImage: ubuntu-16.04

- template: azure-pipelines-uniz-window.yml
  parameters:
    jobName: Windows
    vmImage: vs2017-win2016