jobs:
	- job: ${{ parameters.jobName }}
		pool:
			vmImage: ${{ parameters.vmImage }}
		strategy:
			matrix:
				node_8_x:
					node_version: 8.x
				node_10_x:
					node_version: 10.x
				node_12_x:
					node_version: 10.x

		steps:
			- task: NodeTool@0
				inputs:
					versionSpec: $(node_version)
			- script: |
					npm install -g yarn@latest
				displayName: "Installing yarn"
			- script: |
					yarn
				displayName: "Installing dependencies"
			- script: yarn lint
				displayName: "Linting the code"
			- script: yarn test:ci
				displayName: "Running the tests"